/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.vistas;

import hotelideal.Conexion;
import hotelideal.Habitacion;
import hotelideal.HabitacionData;
import hotelideal.Huesped;
import hotelideal.TipoDeHabitacion;
import hotelideal.TipoDeHabitacionData;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author usuario
 */
public class listadodehabitaciones1 extends javax.swing.JInternalFrame {
    private HabitacionData habitacionData;
    private TipoDeHabitacionData tipoDeHabitacionData;
    private Habitacion habitacion;
    private TipoDeHabitacion tipoDeHabitacion;
    private int numero, piso, max_personas, cant_camas;    
    private boolean estado;
    private double precio_noche;
    private String tipo, tipo_camas;
    private int id_habitacion, id_tipo_de_habitacion;
    private Conexion conexion;
 
    /**
     * Creates new form listadodehabitaciones
     */
    public listadodehabitaciones1() {
        initComponents();
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        listadehabitaciones = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        nuevahabitacion = new javax.swing.JLabel();
        cancelar1 = new javax.swing.JButton();
        jLnumero = new javax.swing.JLabel();
        rBocupado = new javax.swing.JRadioButton();
        rBlibre = new javax.swing.JRadioButton();
        tipodehabitacion = new javax.swing.JLabel();
        jTnumero = new javax.swing.JTextField();
        jTpiso = new javax.swing.JTextField();
        ingresetipo = new javax.swing.JComboBox<>();
        jBguardar = new javax.swing.JButton();
        jLpiso = new javax.swing.JLabel();
        jLestado = new javax.swing.JLabel();

        listadehabitaciones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        listadehabitaciones.setText("Lista de Habitaciones");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        nuevahabitacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nuevahabitacion.setText("Nueva Habitacion");

        cancelar1.setText("Cancelar");
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });

        jLnumero.setText("Numero");

        rBocupado.setText("Ocupado");
        rBocupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBocupadoActionPerformed(evt);
            }
        });

        rBlibre.setText("Libre");
        rBlibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBlibreActionPerformed(evt);
            }
        });

        tipodehabitacion.setText("Tipo de habitacion");

        jTnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnumeroActionPerformed(evt);
            }
        });

        jTpiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpisoActionPerformed(evt);
            }
        });

        ingresetipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estandar Simple", "Doble ", "Triple", "Suite Lujo" }));
        ingresetipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresetipoActionPerformed(evt);
            }
        });

        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jLpiso.setText("Piso");

        jLestado.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(nuevahabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(tipodehabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingresetipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLpiso)
                                    .addComponent(jLestado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTpiso, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rBocupado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rBlibre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBguardar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listadehabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(219, 219, 219)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(cancelar1)))))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nuevahabitacion)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnumero)
                    .addComponent(jTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBguardar)
                    .addComponent(cancelar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTpiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLpiso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBocupado)
                    .addComponent(rBlibre)
                    .addComponent(jLestado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipodehabitacion)
                    .addComponent(ingresetipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Buscar)
                        .addComponent(cancelar))
                    .addComponent(listadehabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
          try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(listadodehabitaciones1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar1ActionPerformed
        // TODO add your handling code here:
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
           Logger.getLogger(panelprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelar1ActionPerformed

    private void rBocupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBocupadoActionPerformed
        // TODO add your handling code here:
        rBlibre.setSelected(false);
        
    }//GEN-LAST:event_rBocupadoActionPerformed

    private void rBlibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBlibreActionPerformed
        // TODO add your handling code here:
        rBocupado.setSelected(false);
    }//GEN-LAST:event_rBlibreActionPerformed

    private void jTnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnumeroActionPerformed

    private void jTpisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpisoActionPerformed

    private void ingresetipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresetipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresetipoActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
        
        TipoDeHabitacion th;
        if (rBocupado.isSelected()){
                    estado=true;
                }else{estado=false;}
                id_tipo_de_habitacion=(int) tblTiposHabitaciones.getValueAt(cel, 0);
                th=new TipoDeHabitacion(id_tipo_de_habitacion);
                numero=Integer.parseInt(jTnumero.getText());
                piso=Integer.parseInt(jTpiso.getText());
                Habitacion habitacion=new Habitacion(numero,piso,estado,th);
                habitacionData.guardarHabitacion(habitacion);
                JOptionPane.showMessageDialog(null, "¡¡Huésped ingresado!!");
        
    }//GEN-LAST:event_jBguardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelar1;
    private javax.swing.JComboBox<String> ingresetipo;
    private javax.swing.JButton jBguardar;
    private javax.swing.JLabel jLestado;
    private javax.swing.JLabel jLnumero;
    private javax.swing.JLabel jLpiso;
    private javax.swing.JTextField jTnumero;
    private javax.swing.JTextField jTpiso;
    private javax.swing.JLabel listadehabitaciones;
    private javax.swing.JLabel nuevahabitacion;
    private javax.swing.JRadioButton rBlibre;
    private javax.swing.JRadioButton rBocupado;
    private javax.swing.JLabel tipodehabitacion;
    // End of variables declaration//GEN-END:variables
}
