/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.vistas;

import hotelideal.Conexion;
import hotelideal.HabitacionData;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author usuario
 */
public class nuevahabitacion extends javax.swing.JInternalFrame {
  private HabitacionData habitacionData;
    private int id_habitacion;
    private Conexion conexion;
    /**
     * Creates new form nuevahabitacion
     */
    public nuevahabitacion() {
        initComponents();
    
       try {
            conexion=new Conexion("jdbc:mysql://localhost/hotelideal1","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(nuevahabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        habitacionData=new HabitacionData(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevahabitacion = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        piso = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        ocupado = new javax.swing.JRadioButton();
        libre = new javax.swing.JRadioButton();
        tipodehabitacion = new javax.swing.JLabel();
        ingresenumero = new javax.swing.JTextField();
        ingresepiso = new javax.swing.JTextField();
        ingresetipo = new javax.swing.JComboBox<>();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        nuevahabitacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nuevahabitacion.setText("Nueva Habitacion");

        numero.setText("Numero");

        piso.setText("Piso");

        estado.setText("Estado");

        ocupado.setText("Ocupado");
        ocupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocupadoActionPerformed(evt);
            }
        });

        libre.setText("Libre");
        libre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libreActionPerformed(evt);
            }
        });

        tipodehabitacion.setText("Tipo de habitacion");

        ingresenumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresenumeroActionPerformed(evt);
            }
        });

        ingresepiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresepisoActionPerformed(evt);
            }
        });

        ingresetipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estandar Simple", "Doble ", "Triple", "Suite Lujo" }));
        ingresetipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresetipoActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(nuevahabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(piso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(39, 39, 39)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ingresenumero, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(ingresepiso)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ocupado)
                                        .addGap(36, 36, 36)
                                        .addComponent(libre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipodehabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ingresetipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(guardar)
                                .addGap(57, 57, 57)
                                .addComponent(cancelar)))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevahabitacion)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero)
                            .addComponent(ingresenumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(piso))
                    .addComponent(ingresepiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado)
                    .addComponent(ocupado)
                    .addComponent(libre))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipodehabitacion)
                    .addComponent(ingresetipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(cancelar))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 

       
    private void ingresepisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresepisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresepisoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void libreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libreActionPerformed

    private void ocupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocupadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocupadoActionPerformed

    private void ingresenumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresenumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresenumeroActionPerformed

    private void ingresetipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresetipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresetipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel estado;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField ingresenumero;
    private javax.swing.JTextField ingresepiso;
    private javax.swing.JComboBox<String> ingresetipo;
    private javax.swing.JRadioButton libre;
    private javax.swing.JLabel nuevahabitacion;
    private javax.swing.JLabel numero;
    private javax.swing.JRadioButton ocupado;
    private javax.swing.JLabel piso;
    private javax.swing.JLabel tipodehabitacion;
    // End of variables declaration//GEN-END:variables
}
